import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CartProvider } from "@/lib/card";
import AgeBanner from "@/components/age-banner";
import { Toaster } from "react-hot-toast";

const font = localFont({
  src: "./fonts/Bold.woff",
  variable: "--font-hussar-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-gradient-to-r from-lime-600 via-yellow-300 to-red-600`}>
        <CartProvider>
          <AgeBanner />
          {children}
          <Toaster
            toastOptions={{
              style: {
                textAlign: "center",
              }
            }}
          />
        </CartProvider>
      </body>
    </html>
  );
}
